version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    build:
      context: frontend
    image: botium/botium-speech-frontend:develop
    restart: always
    volumes:
      - "./frontend/resources:/app/resources"
  watcher:
    build:
      context: watcher
    image: botium/botium-speech-watcher:develop
    restart: always
    volumes:
      - "./watcher:/app/watch"
      - "./logs/watcher:/app/logs"
  stt-en:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.en
    image: botium/botium-speech-kaldi-en:develop
    restart: always
    volumes:
      - "./logs/stt-en:/opt/logs"
  stt-de:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.de
    image: botium/botium-speech-kaldi-de:develop
    restart: always
    volumes:
      - "./logs/stt-de:/opt/logs"
  tts:
    build:
      context: tts
      dockerfile: Dockerfile.marytts
    image: botium/botium-speech-marytts:develop
    restart: always
  dictate:
    build:
      context: dictate
    image: botium/botium-speech-dictate:develop
    restart: always
