version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    image: botium/botium-speech-frontend:latest
    restart: always
    volumes:
      - "./frontend/resources:/app/resources"
  watcher:
    image: botium/botium-speech-watcher:latest
    restart: always
    volumes:
      - "./watcher:/app/watch"
      - "./logs/watcher:/app/logs"
  stt_en:
    image: botium/botium-speech-kaldi-en:latest
    restart: always
    volumes:
      - "./logs/stt_en:/opt/logs"
  stt_de:
    image: botium/botium-speech-kaldi-de:latest
    restart: always
    volumes:
      - "./logs/stt_de:/opt/logs"
  tts:
    image: botium/botium-speech-marytts:latest
    restart: always
  dictate:
    image: botium/botium-speech-dictate:latest
    restart: always
