version: '3'
services:
  frontend:
    build:
      context: .
      args:
        RASA_ENDPOINT: https://demo.botiumbox.com
        RASA_PATH: /rasa-demo/socket.io
    image: botium/botium-speech-rasa-voice
    restart: always
    ports:
      - 4700:8080